### ISSUE TITLE
FMDatabase : duplicate symbols FMDatabase

### ISSUE THREAD

**Issue by cpicot** [ezeeworld/B4S-iOS-SDK#2]
Bonjour,

Avec le SDK B4S 2.0.4 survient deux erreurs de link lors du build : 
- duplicate symbol _FMDBBlockSQLiteCallBackFunction
- duplicate symbol _FMDBExecuteBulkSQLCallback

Nous utilisons dans notre application un autre SDK qui utilise comme le SDK B4S l'Api FMDatabase. Nous n'avons pas la main sur cet autre SDK.

A priori, on peut retirer les .o de FMDatabase de votre Sdk pour que la lib FMDatabase utilisée soit celle de l'autre SDK que nous embarquons. Mais cela pose deux problèmes : 
- Le SDK B4S prefix la lib avec B4S_ ce qui rend impossible cette méthode ;
- Une potentielle différence de version de FMDatabase entre les deux SDKs.

Notre conclusion : Pouvez vous renommer les symboles de FMDatabase (en les préfixant par exemple) ?

Merci,
Clément.

**Comment by freboursier-ez** [comment]
Bonjour,

Le problème est identifié et est en cours de résolution.

Cordialement
Francois

**Comment by freboursier-ez** [comment]
Bonjour,

Ce problème est résolu dans le SDK 2.0.7: https://github.com/ezeeworld/B4S-iOS-SDK/releases/tag/2.0.7
